name: Bandit Scan and Push to Test

on:
  push:
    branches:
      - main

jobs:
  bandit_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.0  # Replace with your Python version

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit Scan
        run: bandit -r .

      - name: Push to Test Repo
        run: |
          git remote add test-repo https://github.com/your-username/test.git
          git push test-repo main
